const map =[
    ["codigoNnuuSunat","HpsaAprobacionFinal","Código NNUU-SUNAT","-","0",""],
    ["crossComplementEnWeb","HpsaAprobacionFinal","CROSS_COMPLEMENT_EN_WEB","","",""],
    ["descripcionCarteleria","HpsaAprobacionFinal","DESCRIPCION_CARTELERIA","","",""],
    ["descripcionFt","HpsaAprobacionFinal","DESCRIPCION_FT","","",""],
    ["descripcionGlovo","HpsaAprobacionFinal","DESCRIPCION_GLOVO","","",""],
    ["descripcionVineta","HpsaAprobacionFinal","DESCRIPCION_VINETA","","",""],
    ["descripcionWebAutomatica","HpsaAprobacionFinal","DESCRIPCION_WEB_AUTOMATICA","","",""],
    ["enriquecerParaSitioWeb","HpsaAprobacionFinal","Enriquecer para Sitio Web","","",""],
   // ["marca","HpsaAprobacionFinal","Marca","","",""],
    ["nombreGlovo","HpsaAprobacionFinal","NOMBRE_GLOVO","","",""],
    ["realizadoComercial","HpsaAtributosAsistente","REALIZADO_COMERCIAL","","",""],
    ["advertenciaDeUso","HpsaAtributosComerciales","Advertencia de uso","","",""],
    ["area","HpsaAtributosComerciales","Área","","",""],
    ["areaText","HpsaAtributosComerciales","Área text","","",""],
    ["areaVtex","HpsaAtributosComerciales","AREA_VTEX","","",""],
    ["caracteristicas","HpsaAtributosComerciales","Características","","",""],
    ["categoriaVtex","HpsaAtributosComerciales","CATEGORIA_VTEX","","",""],
    ["codigoProveedor","HpsaAtributosComerciales","CODIGO_PROVEEDOR","","",""],
    ["color","HpsaAtributosComerciales","Color","","",""],
    ["colorSecundario","HpsaAtributosComerciales","Color secundario","","",""],
    ["compradoPor","HpsaAtributosComerciales","Comprado Por","","",""],
    ["costo","HpsaAtributosComerciales","Costo","","",""],
    ["cpiCross","HpsaAtributosComerciales","CPI_CROSS","","",""],
    ["departamento","HpsaAtributosComerciales","DEPARTAMENTO","","",""],
    ["descripcionCorta","HpsaAtributosComerciales","DESCRIPCION_CORTA","","",""],
    ["descripcionPmm","HpsaAtributosComerciales","Descripción Pmm","","",""],
    ["estadoDelProductoPmm","HpsaAtributosComerciales","Estado Del Producto (Pmm)","","",""],
    ["estadoEnElFlujoPmdm","HpsaAtributosComerciales","Estado en Flujo Step","","",""],
    ["fechaFinCross","HpsaAtributosComerciales","Fecha Fin Cross","","",""],
    ["fechaFinInfaltable","HpsaAtributosComerciales","Fecha Fin Infaltable","","",""],
    ["fechaVigenciaTop2000","HpsaAtributosComerciales","FECHA_VIGENCIA_TOP_2000","","",""],
    ["garantia","HpsaAtributosComerciales","Garantía","","",""],
    ["incluye","HpsaAtributosComerciales","Incluye","","",""],
    ["lineaPromart","HpsaAtributosComerciales","Codigo de Linea PROMART","","",""],
    ["lineaPromartNodoAzul","HpsaAtributosComerciales","LINEA_PROMART_NODO_AZUL","","",""],
    ["margen","HpsaAtributosComerciales","Margen","","",""],
    ["material","HpsaAtributosComerciales","Material","","",""],
    ["modelo","HpsaAtributosComerciales","Modelo","","",""],
    ["moneda","HpsaAtributosComerciales","Moneda","","",""],
    ["mundoInfaltable","HpsaAtributosComerciales","Mundo Infaltable","","",""],
    ["negociacion","HpsaAtributosComerciales","Negociación","","",""],
    ["numeroDePiezas","HpsaAtributosComerciales","Número de piezas","","",""],
    ["observaciones","HpsaAtributosComerciales","Observaciones","","",""],
    ["oc","HpsaAtributosComerciales","OC","","",""],
    ["paisDeManufactura","HpsaAtributosComerciales","País De Manufactura","","",""],
    ["precioUnitario","HpsaAtributosComerciales","Precio Unitario","","",""],
    ["prioridadVenta","HpsaAtributosComerciales","Prioridad Venta","","",""],
    ["procedencia","HpsaAtributosComerciales","Procedencia","","",""],
    ["procedenciaText","HpsaAtributosComerciales","PROCEDENCIA_TEXT","","",""],
    ["publicacionEnWeb","HpsaAtributosComerciales","Publicación en Web","","",""],
    ["razonSocial","HpsaAtributosComerciales","RAZON_SOCIAL","","",""],
    ["recomendacionesDeUso","HpsaAtributosComerciales","Recomendaciones De Uso","","",""],
    ["sku","HpsaAtributosComerciales","Sku","","",""],
    ["skuProveedor","HpsaAtributosComerciales","Sku Proveedor","","",""],
    ["subcategoria4nVtex","HpsaAtributosComerciales","SubCategoria_4N_vtex","","",""],
    ["subcategoriaVtex","HpsaAtributosComerciales","SUBCATEGORIA_VTEX","","",""],
    ["tipoDeMarca","HpsaAtributosComerciales","TIPO_DE_MARCA","","",""],
    ["tipoDeNegociacion","HpsaAtributosComerciales","TIPO_DE_NEGOCIACION","","",""],
    ["top2000","HpsaAtributosComerciales","TOP_2000","","",""],
    ["youtube","HpsaAtributosComerciales","Youtube","","",""],
    ["agoraShop","HpsaAtributosComerciales2","AGORA_SHOP","","",""],
    ["estructuraDeEmpaque","HpsaAtributosComerciales2","ESTRUCTURA_DE_EMPAQUE","","",""],
    ["idYoutube","HpsaAtributosComerciales2","ID Youtube","","",""],
    ["ingresoEspecial","HpsaAtributosComerciales2","INGRESO_ESPECIAL","","",""],
    ["nivelSocioeconOmico","HpsaAtributosComerciales2","NIVEL SOCIOECONÓMICO","","",""],
    ["nuevoTipoDeSurtido","HpsaAtributosComerciales2","Nuevo Tipo de surtido","","",""],
    ["paisDeOrigen","HpsaAtributosComerciales2","País de origen","","",""],
    //["proveedor","HpsaAtributosComerciales2","Proveedor","","",""],
    ["puntoDePrecio","HpsaAtributosComerciales2","Punto de precio","","",""],
    ["sobreInventario","HpsaAtributosComerciales2","Sobre_Inventario","","",""],
    ["subTipoDeProducto","HpsaAtributosComerciales2","Sub Tipo de Producto","","",""],
    ["textoError","HpsaAtributosComerciales2","Texto error","","",""],
    ["tipoDeProducto","HpsaAtributosComerciales2","Tipo de Producto","","",""],
    ["tipoDeSurtido","HpsaAtributosComerciales2","Tipo de surtido","","",""],
    ["tipoDeVentaDeProducto","HpsaAtributosComerciales2","Tipo de venta de producto","","",""],
    ["unidadDeMedidaDeVenta","HpsaAtributosComerciales2","Unidad de Medida de venta","","",""],
    ["afectoDetraccion","HpsaAtributosContables","Afecto Detracción","","",""],
    ["afectoIgv","HpsaAtributosContables","Afecto IGV","","",""],
    ["afectoPercep","HpsaAtributosContables","Afecto Percep","","",""],
    ["advertenciaDeUso","HpsaAtributosContenido1","Advertencia de uso","","",""],
    ["alturaDeZocalo","HpsaAtributosContenido1","Altura de zócalo","","",""],
    ["alturaMaximaProducto","HpsaAtributosContenido1","Altura máxima producto","","",""],
    ["alturaMinimaReposabrazos","HpsaAtributosContenido1","Altura mínima reposabrazos","","",""],
    ["arranqueEnCaliente","HpsaAtributosContenido1","Arranque en caliente","","",""],
    ["autolimpiante","HpsaAtributosContenido1","Autolimpiante","","",""],
    ["avances","HpsaAtributosContenido1","Avances","","",""],
    ["camaraPrincipal","HpsaAtributosContenido1","Cámara principal","","",""],
    ["cantidadDePaneles","HpsaAtributosContenido1","Cantidad de paneles","","",""],
    ["capacidadDeCorteEnAluminio","HpsaAtributosContenido1","Capacidad de corte en aluminio","","",""],
    ["capacidadDelCongelador","HpsaAtributosContenido1","Capacidad del congelador","","",""],
    ["compatibilidadGriferia","HpsaAtributosContenido1","Compatibilidad grifería","","",""],
    ["composicionQuimica","HpsaAtributosContenido1","Composición química","","",""],
    ["consumoDeEnergia","HpsaAtributosContenido1","Consumo de energía","","",""],
    ["dientesPorPulgada","HpsaAtributosContenido1","Dientes por pulgada","","",""],
    ["discoDuroSolido","HpsaAtributosContenido1","Disco duro sólido","","",""],
    ["exposicion","HpsaAtributosContenido1","Exposición","","",""],
    ["formaDeSiembra","HpsaAtributosContenido1","Forma de siembra","","",""],
    ["formatosDeReproduccion","HpsaAtributosContenido1","Formatos de reproducción","","",""],
    ["hidroresistente","HpsaAtributosContenido1","Hidroresistente","","",""],
    ["lavadoAVapor","HpsaAtributosContenido1","Lavado a vapor","","",""],
    ["lentes3d","HpsaAtributosContenido1","Lentes 3D","","",""],
    ["materialDeAislante","HpsaAtributosContenido1","Material de aislante","","",""],
    ["materiales","HpsaAtributosContenido1","Materiales","","",""],
    ["medidaDeProductosEnCombo","HpsaAtributosContenido1","Medida de productos en combo","","",""],
    ["medidasDeCajones","HpsaAtributosContenido1","Medidas de cajones","","",""],
    ["memoriaExpandible","HpsaAtributosContenido1","Memoria expandible","","",""],
    ["metodoDeAplicacion","HpsaAtributosContenido1","Método de aplicación","","",""],
    ["modeloDeMotor","HpsaAtributosContenido1","Modelo de motor","","",""],
    ["numeroCertificadoEficienciaEne","HpsaAtributosContenido1","Número certificado eficiencia energética","","",""],
    ["numeroDeDientes","HpsaAtributosContenido1","Número de dientes","","",""],
    ["pedal","HpsaAtributosContenido1","Pedal","","",""],
    ["protectorAntiruido","HpsaAtributosContenido1","Protector antiruido","","",""],
    ["resolucionDePantalla","HpsaAtributosContenido1","Resolución de pantalla","","",""],
    ["resolucionVideo","HpsaAtributosContenido1","Resolución video","","",""],
    ["seguroParaNinos","HpsaAtributosContenido1","Seguro para niños","","",""],
    ["seleccionDeTiempoDeSecado","HpsaAtributosContenido1","Selección de tiempo de secado","","",""],
    ["sintonizadorDigital","HpsaAtributosContenido1","Sintonizador Digital","","",""],
    ["sistema","HpsaAtributosContenido1","Sistema","","",""],
    ["tapa","HpsaAtributosContenido1","Tapa","","",""],
    ["tipoDeCampana","HpsaAtributosContenido1","Tipo de campana","","",""],
    ["tipoDeChorros","HpsaAtributosContenido1","Tipo de chorros","","",""],
    ["velocidadDelProcesador","HpsaAtributosContenido1","Velocidad del procesador","","",""],
    ["visera","HpsaAtributosContenido1","Visera","","",""],
    ["acabadoDeLaManija","HpsaAtributosContenido10","Acabado de la manija","","",""],
    ["acabadoDePuertas","HpsaAtributosContenido10","Acabado de puertas","","",""],
    ["acabadoDelVidrio","HpsaAtributosContenido10","Acabado del vidrio","","",""],
    ["acolchado","HpsaAtributosContenido10","Acolchado","","",""],
    ["antideslizante","HpsaAtributosContenido10","Antideslizante","","",""],
    ["apoyaBrazos","HpsaAtributosContenido10","Apoya brazos","","",""],
    ["bateria","HpsaAtributosContenido10","Batería","","",""],
    ["bisagras","HpsaAtributosContenido10","Bisagras","","",""],
    ["camaraIntegrada","HpsaAtributosContenido10","Cámara integrada","","",""],
    ["cambioMecanico","HpsaAtributosContenido10","Cambio mecánico","","",""],
    ["capacidadConductivaTermica","HpsaAtributosContenido10","Capacidad conductiva térmica","","",""],
    ["composicionOrigen","HpsaAtributosContenido10","Composición/Origen","","",""],
    ["compresor","HpsaAtributosContenido10","Compresor","","",""],
    ["conexionWiFi","HpsaAtributosContenido10","Conexión Wi Fi","","",""],
    ["depositoDeAguaDesmontable","HpsaAtributosContenido10","Depósito de agua desmontable","","",""],
    ["dispensadorDeAgua","HpsaAtributosContenido10","Dispensador de agua","","",""],
    ["distanciaEntrePuas","HpsaAtributosContenido10","Distancia entre púas","","",""],
    ["espacioParaParlantes","HpsaAtributosContenido10","Espacio para parlantes","","",""],
    ["espesorDeCuerpo","HpsaAtributosContenido10","Espesor de cuerpo","","",""],
    ["giroDeCierre","HpsaAtributosContenido10","Giro de cierre","","",""],
    ["lente","HpsaAtributosContenido10","Lente","","",""],
    ["luzInterior","HpsaAtributosContenido10","Luz interior","","",""],
    ["materialDeAsiento","HpsaAtributosContenido10","Material de asiento","","",""],
    ["materialDelMango","HpsaAtributosContenido10","Material del mango","","",""],
    ["materialDelTablero","HpsaAtributosContenido10","Material del tablero","","",""],
    ["materialDeBroche","HpsaAtributosContenido10","Material  De Broche","","",""],
    ["moldeable","HpsaAtributosContenido10","Moldeable","","",""],
    ["numeroDePiezas","HpsaAtributosContenido10","Número de piezas","","",""],
    ["numeroDeSillas","HpsaAtributosContenido10","Número de Sillas","","",""],
    ["plazas","HpsaAtributosContenido10","Plazas","","",""],
    ["porcentajeDeGerminacion","HpsaAtributosContenido10","Porcentaje de germinación","","",""],
    ["proteccionUv","HpsaAtributosContenido10","Protección UV","","",""],
    ["resolucionDeImagen","HpsaAtributosContenido10","Resolución de imagen","","",""],
    ["retencionDeCompuestosQuimicos","HpsaAtributosContenido10","Retención de compuestos químicos","","",""],
    ["reversible","HpsaAtributosContenido10","Reversible","","",""],
    ["sistemaDeDescarga","HpsaAtributosContenido10","Sistema de descarga","","",""],
    ["tamanoEntradaDeAire","HpsaAtributosContenido10","Tamaño entrada de aire","","",""],
    ["tecladoIluminado","HpsaAtributosContenido10","Teclado iluminado","","",""],
    ["tipoDeBoquillas","HpsaAtributosContenido10","Tipo de boquillas","","",""],
    ["tipoDeFuncion","HpsaAtributosContenido10","Tipo de función","","",""],
    ["tipoDeLaser","HpsaAtributosContenido10","Tipo de láser","","",""],
    ["tipoDeMedidas","HpsaAtributosContenido10","Tipo de medidas","","",""],
    ["tipoDeParrilla","HpsaAtributosContenido10","Tipo de parrilla","","",""],
    ["tipoDeTablero","HpsaAtributosContenido10","Tipo de Tablero","","",""],
    ["antiacaros","HpsaAtributosContenido11","Antiacaros","","",""],
    ["autoperforante","HpsaAtributosContenido11","Autoperforante","","",""],
    ["capacidadDePersonas","HpsaAtributosContenido11","Capacidad de personas","","",""],
    ["colorDeAspas","HpsaAtributosContenido11","Color de aspas","","",""],
    ["colorDeCuerpo","HpsaAtributosContenido11","Color de cuerpo","","",""],
    ["colorDeLuz","HpsaAtributosContenido11","Color de luz","","",""],
    ["controlDeLuz","HpsaAtributosContenido11","Control de luz","","",""],
    ["correaAjustable","HpsaAtributosContenido11","Correa ajustable","","",""],
    ["corteDeIngleteDeGradoMaximoDer","HpsaAtributosContenido11","Corte de inglete de grado máximo - derecha","","",""],
    ["dispensadorDeHielo","HpsaAtributosContenido11","Dispensador de hielo","","",""],
    ["epocaDeSiembra","HpsaAtributosContenido11","Época de siembra","","",""],
    ["espacioParaDvdDecodificador","HpsaAtributosContenido11","Espacio para DVD/Decodificador","","",""],
    ["flujoDeAireInverso","HpsaAtributosContenido11","Flujo de aire inverso","","",""],
    ["formaDeLaTaza","HpsaAtributosContenido11","Forma de la taza","","",""],
    ["formaDelPanel","HpsaAtributosContenido11","Forma del panel","","",""],
    ["guiaLaser","HpsaAtributosContenido11","Guía láser","","",""],
    ["ladoDeAbertura","HpsaAtributosContenido11","Lado de abertura","","",""],
    ["materialDeLaEstructura","HpsaAtributosContenido11","Material de la estructura","","",""],
    ["materialDeLasParrillas","HpsaAtributosContenido11","Material de las parrillas","","",""],
    ["materialDeResorte","HpsaAtributosContenido11","Material de resorte","","",""],
    ["memoriaInterna","HpsaAtributosContenido11","Memoria interna","","",""],
    ["nivelDeProteccion","HpsaAtributosContenido11","Nivel de protección","","",""],
    ["nivelesDePotencia","HpsaAtributosContenido11","Niveles de potencia","","",""],
    ["numeroDeBandejas","HpsaAtributosContenido11","Número de bandejas","","",""],
    ["numeroDeEntradasUsb","HpsaAtributosContenido11","Número de entradas USB","","",""],
    ["numeroDeEntradasVideocomponent","HpsaAtributosContenido11","Número de entradas videocomponente","","",""],
    ["numeroDeEstantes","HpsaAtributosContenido11","Número de estantes","","",""],
    ["numeroDeHilos","HpsaAtributosContenido11","Número de hilos","","",""],
    ["numeroDePerchas","HpsaAtributosContenido11","Número de perchas","","",""],
    ["numeroDeProgramasDeLavado","HpsaAtributosContenido11","Número de programas de lavado","","",""],
    ["numeroDeVelocidades","HpsaAtributosContenido11","Número de velocidades","","",""],
    ["presionDeAgua","HpsaAtributosContenido11","Presión de agua","","",""],
    ["punteraDeSeguridad","HpsaAtributosContenido11","Puntera de seguridad","","",""],
    ["rebose","HpsaAtributosContenido11","Rebose","","",""],
    ["reguladorDeTemperatura","HpsaAtributosContenido11","Regulador de temperatura","","",""],
    ["resistenteALaCorrosion","HpsaAtributosContenido11","Resistente a la corrosión","","",""],
    ["sistemaDeFuncionamiento","HpsaAtributosContenido11","Sistema de funcionamiento","","",""],
    ["tamanoPantallaCelulares","HpsaAtributosContenido11","Tamaño pantalla celulares","","",""],
    ["temporizador","HpsaAtributosContenido11","Temporizador","","",""],
    ["tipoDeCorte","HpsaAtributosContenido11","Tipo de corte","","",""],
    ["tipoDeEspacio","HpsaAtributosContenido11","Tipo de espacio","","",""],
    ["tipoDeFoco","HpsaAtributosContenido11","Tipo de foco","","",""],
    ["tipoDePerfil","HpsaAtributosContenido11","Tipo de perfil","","",""],
    ["tipoDePiston","HpsaAtributosContenido11","Tipo de pistón","","",""],
    ["tipoDeTecnologia","HpsaAtributosContenido11","Tipo de tecnología","","",""],
    ["agenteExtintor","HpsaAtributosContenido12","Agente extintor","","",""],
    ["alarmaDePuertaAbierta","HpsaAtributosContenido12","Alarma de puerta abierta","","",""],
    ["cargadorDeBateria","HpsaAtributosContenido12","Cargador de batería","","",""],
    ["cerrojoInferior","HpsaAtributosContenido12","Cerrojo inferior","","",""],
    ["cloro","HpsaAtributosContenido12","Cloro","","",""],
    ["colorDePuertas","HpsaAtributosContenido12","Color de puertas","","",""],
    ["conexionBluetooth","HpsaAtributosContenido12","Conexión Bluetooth","","",""],
    ["controlDeTemperatura","HpsaAtributosContenido12","Control de temperatura","","",""],
    ["dielectrico","HpsaAtributosContenido12","Dieléctrico","","",""],
    ["dualSim","HpsaAtributosContenido12","Dual SIM","","",""],
    ["extensible","HpsaAtributosContenido12","Extensible","","",""],
    ["formaDeBase","HpsaAtributosContenido12","Forma de base","","",""],
    ["formaDelGrass","HpsaAtributosContenido12","Forma del grass","","",""],
    ["formato","HpsaAtributosContenido12","Formato","","",""],
    ["largoMinimo","HpsaAtributosContenido12","Largo máximo","","",""],
    ["ledIntegrado","HpsaAtributosContenido12","Largo mínimo","","",""],
    ["mantenimientoDeFlujoLuminoso","HpsaAtributosContenido12","Mantenimiento de Flujo Luminoso","","",""],
    ["marco","HpsaAtributosContenido12","Marco","","",""],
    ["materialDeBisagras","HpsaAtributosContenido12","Material de bisagras","","",""],
    ["materialDeCorrederas","HpsaAtributosContenido12","Material de correderas","","",""],
    ["materialDeLaBarra","HpsaAtributosContenido12","Material de la barra","","",""],
    ["numeroDeCombinaciones","HpsaAtributosContenido12","Número de combinaciones","","",""],
    ["numeroDeCompartimientos","HpsaAtributosContenido12","Número de compartimientos","","",""],
    ["numeroDeParrillasEnHorno","HpsaAtributosContenido12","Número de parrillas en horno","","",""],
    ["numeroDePatas","HpsaAtributosContenido12","Número de patas","","",""],
    ["pantallaSmart","HpsaAtributosContenido12","Pantalla smart","","",""],
    ["pantallaTouch","HpsaAtributosContenido12","Pantalla touch","","",""],
    ["plaga","HpsaAtributosContenido12","Plaga","","",""],
    ["posavasos","HpsaAtributosContenido12","Posavasos","","",""],
    ["puntosDeAbastecimientoEnSimult","HpsaAtributosContenido12","Puntos de abastecimiento en simultaneo","","",""],
    ["reclinable","HpsaAtributosContenido12","Reclinable","","",""],
    ["regualdorDeCaudal","HpsaAtributosContenido12","Regualdor de caudal","","",""],
    ["remolcable","HpsaAtributosContenido12","Remolcable","","",""],
    ["resistenciaALaAbrasion","HpsaAtributosContenido12","Resistencia a la abrasión","","",""],
    ["resistenciaALaCompresion","HpsaAtributosContenido12","Resistencia a la compresión","","",""],
    ["resistenciaAlImpacto","HpsaAtributosContenido12","Resistencia al impacto","","",""],
    ["resistenciaAlMoho","HpsaAtributosContenido12","Resistencia al moho","","",""],
    ["resistenciaRayosUv","HpsaAtributosContenido12","Resistencia rayos UV","","",""],
    ["salvamotor","HpsaAtributosContenido12","Salvamotor","","",""],
    ["talla","HpsaAtributosContenido12","Talla","","",""],
    ["tipoDeBateria","HpsaAtributosContenido12","Tipo de batería","","",""],
    ["tipoDeGrapa","HpsaAtributosContenido12","Tipo de grapa","","",""],
    ["trinqueteReversible","HpsaAtributosContenido12","Trinquete reversible","","",""],
    ["antiEmpanante","HpsaAtributosContenido13","Anti empañante","","",""],
    ["antiInterferencia","HpsaAtributosContenido13","Anti interferencia","","",""],
    ["autonomia","HpsaAtributosContenido13","Autonomía","","",""],
    ["cabecera","HpsaAtributosContenido13","Cabecera","","",""],
    ["capacidadDeElectrodo","HpsaAtributosContenido13","Capacidad de electrodo","","",""],
    ["cerrojoSuperior","HpsaAtributosContenido13","Cerrojo superior","","",""],
    ["concentracion","HpsaAtributosContenido13","Concentración","","",""],
    ["conexionARedElectrica","HpsaAtributosContenido13","Conexión a red eléctrica","","",""],
    ["dosisRecomendada","HpsaAtributosContenido13","Dosis recomendada","","",""],
    ["envase","HpsaAtributosContenido13","Envase","","",""],
    ["espesorMaximo","HpsaAtributosContenido13","Espesor máximo","","",""],
    ["focoLuminiscente","HpsaAtributosContenido13","Foco luminiscente","","",""],
    ["formaDelFoco","HpsaAtributosContenido13","Forma del foco","","",""],
    ["gasRefrigerante","HpsaAtributosContenido13","Gas refrigerante","","",""],
    ["indicadorDeTemperatura","HpsaAtributosContenido13","Indicador de temperatura","","",""],
    ["inflable","HpsaAtributosContenido13","Inflable","","",""],
    ["inflamable","HpsaAtributosContenido13","Inflamable","","",""],
    ["manillas","HpsaAtributosContenido13","Manillas","","",""],
    ["materialDeAcabado","HpsaAtributosContenido13","Material de acabado","","",""],
    ["materialDeBaseDelCajon","HpsaAtributosContenido13","Material de base del cajón","","",""],
    ["materialDeCerdas","HpsaAtributosContenido13","Material de cerdas","","",""],
    ["materialDeCierre","HpsaAtributosContenido13","Material de cierre","","",""],
    ["materialDeLaBandeja","HpsaAtributosContenido13","Material de la bandeja","","",""],
    ["materialDeLaSalida","HpsaAtributosContenido13","Material de la salida","","",""],
    ["numeroDeCuchillas","HpsaAtributosContenido13","Número de cuchillas","","",""],
    ["numeroDeMelodias","HpsaAtributosContenido13","Número de melodías","","",""],
    ["orientacion","HpsaAtributosContenido13","Orientación","","",""],
    ["piezasPorCaja","HpsaAtributosContenido13","Piezas por caja","","",""],
    ["porcentajeDePurificacion","HpsaAtributosContenido13","Porcentaje de purificación","","",""],
    ["portafotos","HpsaAtributosContenido13","Portafotos","","",""],
    ["proteccion","HpsaAtributosContenido13","Protección","","",""],
    ["purificadorDeAire","HpsaAtributosContenido13","Purificador de aire","","",""],
    ["recubrimientoDelMango","HpsaAtributosContenido13","Recubrimiento del mango","","",""],
    ["retencionDeSolidosEnSuspension","HpsaAtributosContenido13","Retención de sólidos en suspensión","","",""],
    ["sistemaOds","HpsaAtributosContenido13","Sistema ODS","","",""],
    ["sistemaOperativo","HpsaAtributosContenido13","Sistema operativo","","",""],
    ["tamanoDePua","HpsaAtributosContenido13","Tamaño de púa","","",""],
    ["termocupla","HpsaAtributosContenido13","Termocupla","","",""],
    ["tiempoDeUso","HpsaAtributosContenido13","Tiempo de uso","","",""],
    ["tipoDeCarpa","HpsaAtributosContenido13","Tipo de carpa","","",""],
    ["tipoDeConduccionTermica","HpsaAtributosContenido13","Tipo de conducción térmica","","",""],
    ["tipoDeInodoro","HpsaAtributosContenido13","Tipo de inodoro","","",""],
    ["tipoDeMotor","HpsaAtributosContenido13","Tipo de motor","","",""],
    ["tipoDeTerminal","HpsaAtributosContenido13","Tipo de terminal","","",""],
    ["vibracionesPorMinuto","HpsaAtributosContenido13","Vibraciones por minuto","","",""],
    ["acabadoDelMarco","HpsaAtributosContenido14","Acabado del marco","","",""],
    ["ajusteDePotencia","HpsaAtributosContenido14","Ajuste de potencia","","",""],
    ["ambiente","HpsaAtributosContenido14","Ambiente","","",""],
    ["aptoParaLavadora","HpsaAtributosContenido14","Apto para lavadora","","",""],
    ["autoadhesivos","HpsaAtributosContenido14","Autoadhesivos","","",""],
    ["centrifugado","HpsaAtributosContenido14","Centrifugado","","",""],
    ["clasificacionAws","HpsaAtributosContenido14","Clasificación AWS","","",""],
    ["dobleHoja","HpsaAtributosContenido14","Doble hoja","","",""],
    ["espejo","HpsaAtributosContenido14","Espejo","","",""],
    ["estadoDelContenido","HpsaAtributosContenido14","Estado del contenido","","",""],
    ["estructuraInterna","HpsaAtributosContenido14","Estructura interna","","",""],
    ["forma","HpsaAtributosContenido14","Forma","","",""],
    ["hojaExtraible","HpsaAtributosContenido14","Hoja extraíble","","",""],
    ["largoDelCarril","HpsaAtributosContenido14","Largo del carril","","",""],
    ["materialDelTanque","HpsaAtributosContenido14","Material del tanque","","",""],
    ["mecanismoDeApertura","HpsaAtributosContenido14","Mecanismo de apertura","","",""],
    ["nivelDeCorrosion","HpsaAtributosContenido14","Nivel de corrosión","","",""],
    ["nivelDeSeguridad","HpsaAtributosContenido14","Nivel de seguridad","","",""],
    ["nombreCientifico","HpsaAtributosContenido14","Nombre científico","","",""],
    ["numeroDeEntradasVga","HpsaAtributosContenido14","Número de entradas VGA","","",""],
    ["plegable","HpsaAtributosContenido14","Plegable","","",""],
    ["presionMinimaDeAguaDeAlimentac","HpsaAtributosContenido14","Presión mínima de agua de alimentación","","",""],
    ["resistenteALaTranccion","HpsaAtributosContenido14","Resistente a la trancción","","",""],
    ["reutilizable","HpsaAtributosContenido14","Reutilizable","","",""],
    ["seguroDeBoton","HpsaAtributosContenido14","Seguro De Botón","","",""],
    ["sistemaDeAutoregado","HpsaAtributosContenido14","Sistema de autoregado","","",""],
    ["sistemaDeMarcoInterno","HpsaAtributosContenido14","Sistema de marco interno","","",""],
    ["tarjetaDeVideo","HpsaAtributosContenido14","Tarjeta de video","","",""],
    ["timbre","HpsaAtributosContenido14","Timbre","","",""],
    ["tipoDeGriferia","HpsaAtributosContenido14","Tipo de grifería","","",""],
    ["tipoDeInstalacion","HpsaAtributosContenido14","Tipo de instalación","","",""],
    ["tipoDePlanta","HpsaAtributosContenido14","Tipo de planta","","",""],
    ["tipoDeSalida","HpsaAtributosContenido14","Tipo de salida","","",""],
    ["tipoDeTejido","HpsaAtributosContenido14","Tipo de tejido","","",""],
    ["trafico","HpsaAtributosContenido14","Tráfico","","",""],
    ["tratamientoUv","HpsaAtributosContenido14","Tratamiento UV","","",""],
    ["valvulaDeFuga","HpsaAtributosContenido14","Válvula de fuga","","",""],
    ["velocidadDeTransferencia","HpsaAtributosContenido14","Velocidad de transferencia","","",""],
    ["velocidadVariable","HpsaAtributosContenido14","Velocidad variable","","",""],
    ["velocidades","HpsaAtributosContenido14","Velocidades","","",""],
    ["arranqueEnFrio","HpsaAtributosContenido15","Arranque en frío","","",""],
    ["capacidadDePesoDelTecho","HpsaAtributosContenido15","Capacidad de peso del techo","","",""],
    ["capacidadDePesoPorRepisa","HpsaAtributosContenido15","Capacidad de peso por repisa","","",""],
    ["diametroDeDistribucion","HpsaAtributosContenido15","Diámetro de distribución","","",""],
    ["diametroDeSalida","HpsaAtributosContenido15","Diámetro de salida","","",""],
    ["diametroInterno","HpsaAtributosContenido15","Diámetro interno","","",""],
    ["diametroMaximoDePerforacionEnA","HpsaAtributosContenido15","Diámetro máximo de perforación en acero/metal","","",""],
    ["flujoDeAire","HpsaAtributosContenido15","Flujo de aire","","",""],
    ["gradoDeInclinacion","HpsaAtributosContenido15","Grado de inclinación","","",""],
    ["impactosPorMinuto","HpsaAtributosContenido15","Impactos por minuto","","",""],
    ["largoDeBarra","HpsaAtributosContenido15","Largo de barra","","",""],
    ["largoDeLaHoja","HpsaAtributosContenido15","Largo de la hoja","","",""],
    ["longitudDeCable","HpsaAtributosContenido15","Longitud de Cable","","",""],
    ["mandril","HpsaAtributosContenido15","Mandril","","",""],
    ["mantieneElAguaCalientePor","HpsaAtributosContenido15","Mantiene el agua caliente por","","",""],
    ["materialDeTiradores","HpsaAtributosContenido15","Material de tiradores","","",""],
    ["maximoFlujoDeAguaFiltrada","HpsaAtributosContenido15","Máximo flujo de agua filtrada","","",""],
    ["medida","HpsaAtributosContenido15","Medida","","",""],
    ["medidaDeLaLija","HpsaAtributosContenido15","Medida de la lija","","",""],
    ["medidasDelTanque","HpsaAtributosContenido15","Medidas del tanque","","",""],
    ["movimientosPorMinutoSpm","HpsaAtributosContenido15","Movimientos por minuto (spm)","","",""],
    ["parDeGiroMaximo","HpsaAtributosContenido15","Par de giro máximo","","",""],
    ["pesoDeLaCabeza","HpsaAtributosContenido15","Peso de la cabeza","","",""],
    ["poderResidual","HpsaAtributosContenido15","Poder residual","","",""],
    ["presionMaximaDeTrabajo","HpsaAtributosContenido15","Presión máxima de trabajo","","",""],
    ["presionMinimaDeTrabajo","HpsaAtributosContenido15","Presión mínima de trabajo","","",""],
    ["profundidadDeLaPoza","HpsaAtributosContenido15","Profundidad de la poza","","",""],
    ["profundidadDeRebaje","HpsaAtributosContenido15","Profundidad de rebaje","","",""],
    ["rangoDeAmperaje","HpsaAtributosContenido15","Rango de amperaje","","",""],
    ["rendimiento","HpsaAtributosContenido15","Rendimiento","","",""],
    ["tamanoDeHornillas","HpsaAtributosContenido15","Tamaño de hornillas","","",""],
    ["tensionDelServicio","HpsaAtributosContenido15","Tensión del servicio","","",""],
    ["tiempoDeAlmacenamiento","HpsaAtributosContenido15","Tiempo de almacenamiento","","",""],
    ["tiempoDeCarga","HpsaAtributosContenido15","Tiempo de carga","","",""],
    ["tipoDeMontaje","HpsaAtributosContenido15","Tipo de montaje","","",""],
    ["tipoDeRefrigeradora","HpsaAtributosContenido15","Tipo de refrigeradora","","",""],
    ["torqueMaximo","HpsaAtributosContenido15","Torque máximo","","",""],
    ["velocidad","HpsaAtributosContenido15","Velocidad","","",""],
    ["velocidadSinCarga","HpsaAtributosContenido15","Velocidad sin carga","","",""],
    ["voltaje","HpsaAtributosContenido15","Voltaje","","",""],
    ["abrasividad","HpsaAtributosContenido16","Abrasividad","","",""],
    ["alcance","HpsaAtributosContenido16","Alcance","","",""],
    ["amperaje","HpsaAtributosContenido16","Amperaje","","",""],
    ["anchoDePunta","HpsaAtributosContenido16","Ancho de punta","","",""],
    ["aperturaMaxima","HpsaAtributosContenido16","Apertura Máxima","","",""],
    ["areaDeCobertura","HpsaAtributosContenido16","Área de cobertura","","",""],
    ["capacidad","HpsaAtributosContenido16","Capacidad","","",""],
    ["capacidadDeCorte","HpsaAtributosContenido16","Capacidad de corte","","",""],
    ["capacidadDeExtension","HpsaAtributosContenido16","Capacidad de extensión","","",""],
    ["capacidadDePesoDeLaBase","HpsaAtributosContenido16","Capacidad de peso de la base","","",""],
    ["capacidadDelTanque","HpsaAtributosContenido16","Capacidad del tanque","","",""],
    ["caudal","HpsaAtributosContenido16","Caudal","","",""],
    ["caudalMaximo","HpsaAtributosContenido16","Caudal máximo","","",""],
    ["cicloVegetativo","HpsaAtributosContenido16","Ciclo vegetativo","","",""],
    ["cri","HpsaAtributosContenido16","CRI","","",""],
    ["diametro","HpsaAtributosContenido16","Diámetro","","",""],
    ["diametroNominal","HpsaAtributosContenido16","Diámetro nominal","","",""],
    ["drenaje","HpsaAtributosContenido16","Drenaje","","",""],
    ["encastreYMedidas","HpsaAtributosContenido16","Encastre y medidas","","",""],
    ["espesor","HpsaAtributosContenido16","Espesor","","",""],
    ["frecuencia","HpsaAtributosContenido16","Frecuencia","","",""],
    ["humedad","HpsaAtributosContenido16","Humedad","","",""],
    ["largoDeLaMesa","HpsaAtributosContenido16","Largo de la mesa","","",""],
    ["litrosPorDescarga","HpsaAtributosContenido16","Litros por descarga","","",""],
    ["litrosPorMinuto","HpsaAtributosContenido16","Litros por minuto","","",""],
    ["longitud","HpsaAtributosContenido16","Longitud","","",""],
    ["lumenes","HpsaAtributosContenido16","Lúmenes","","",""],
    ["mantenimientoDelFiltro","HpsaAtributosContenido16","Mantenimiento del filtro","","",""],
    ["medidasDelDisco","HpsaAtributosContenido16","Medidas del disco","","",""],
    ["potenciaDeHornillas","HpsaAtributosContenido16","Potencia de hornillas","","",""],
    ["potenciaNominalDeEntrada","HpsaAtributosContenido16","Potencia nominal de entrada","","",""],
    ["potenciaRealDeAspiracion","HpsaAtributosContenido16","Potencia real de aspiración","","",""],
    ["precisionHpsa","HpsaAtributosContenido16","Precisión","","",""],
    ["presionDeTrabajo","HpsaAtributosContenido16","Presión de trabajo","","",""],
    ["resistencia","HpsaAtributosContenido16","Resistencia","","",""],
    ["tamanoDeCuchilla","HpsaAtributosContenido16","Tamaño de cuchilla","","",""],
    ["tasaDePercusion","HpsaAtributosContenido16","Tasa de percusión","","",""],
    ["tdp","HpsaAtributosContenido16","TDP","","",""],
    ["tiempoDeGerminacion","HpsaAtributosContenido16","Tiempo de germinación","","",""],
    ["tiempoDeSecado","HpsaAtributosContenido16","Tiempo de secado","","",""],
    ["alturaDelAsiento","HpsaAtributosContenido17","Altura del asiento","","",""],
    ["alturaRecomendableDeDistribuci","HpsaAtributosContenido17","Altura recomendable de distribución","","",""],
    ["anchoDeLaMesa","HpsaAtributosContenido17","Ancho de la mesa","","",""],
    ["anchoReclinado","HpsaAtributosContenido17","Ancho reclinado","","",""],
    ["capacidadDeFiltrado","HpsaAtributosContenido17","Capacidad de filtrado","","",""],
    ["capacidadDePesoPorCanasta","HpsaAtributosContenido17","Capacidad de peso por canasta","","",""],
    ["capacidadDelContenedor","HpsaAtributosContenido17","Capacidad del contenedor","","",""],
    ["capacidadDelRecipiente","HpsaAtributosContenido17","Capacidad del recipiente","","",""],
    ["capacidadTotalUtil","HpsaAtributosContenido17","","","",""],
    ["coberturaDeRiego","HpsaAtributosContenido17","","","",""],
    ["diametroDeSuccion","HpsaAtributosContenido17","Diámetro de succión","","",""],
    ["diametroDelDisco","HpsaAtributosContenido17","Diámetro del disco","","",""],
    ["diametroExterno","HpsaAtributosContenido17","Diámetro externo","","",""],
    ["diametroMaximoDePerforacionEnM","HpsaAtributosContenido17","Diámetro máximo de perforación en madera","","",""],
    ["dosificacion","HpsaAtributosContenido17","Dosificación","","",""],
    ["edad","HpsaAtributosContenido17","Edad","","",""],
    ["equivalenciaLuminosa","HpsaAtributosContenido17","","","",""],
    ["flujoMaximo","HpsaAtributosContenido17","Flujo máximo","","",""],
    ["fuerzaDeImpacto","HpsaAtributosContenido17","Fuerza de impacto","","",""],
    ["horasDeDuracion","HpsaAtributosContenido17","","","",""],
    ["inclinacionDelTrompo","HpsaAtributosContenido17","","","",""],
    ["largoDeLaManguera","HpsaAtributosContenido17","","","",""],
    ["largoMaximo","HpsaAtributosContenido17","","","",""],
    ["maximoDeSuccion","HpsaAtributosContenido17","","","",""],
    ["maximoPoderDeDescarga","HpsaAtributosContenido17","","","",""],
    ["medidaDeEntradaDeAgua","HpsaAtributosContenido17","","","",""],
    ["medidasLargoExtendida","HpsaAtributosContenido17","","","",""],
    ["medidasDelPanel","HpsaAtributosContenido17","Medidas del panel","","",""],
    ["nivelDeRuido","HpsaAtributosContenido17","Nivel de ruido","","",""],
    ["nivelesDeTemperatura","HpsaAtributosContenido17","Niveles de temperatura","","",""],
    ["potencia","HpsaAtributosContenido17","Potencia","","",""],
    ["potenciaHp","HpsaAtributosContenido17","","","",""],
    ["profundidadMaximaDeCorte45","HpsaAtributosContenido17","Profundidad máxima de corte 45°","","",""],
    ["rendimientoPorCaja","HpsaAtributosContenido17","","","",""],
    ["resistenciaMaximaVoltaje","HpsaAtributosContenido17","","","",""],
    ["tamanoDeLaPantalla","HpsaAtributosContenido17","Tamaño de la pantalla","","",""],
    ["temperaturaMaxima","HpsaAtributosContenido17","","","",""],
    ["temperaturaMinima","HpsaAtributosContenido17","","","",""],
    ["tiempoDeCalentamiento","HpsaAtributosContenido17","Tiempo de calentamiento","","",""],
    ["voltajeDeSalida","HpsaAtributosContenido17","Voltaje De Salida","","",""],
    ["altoConBase","HpsaAtributosContenido18","","","",""],
    ["alturaDeLaTaza","HpsaAtributosContenido18","","","",""],
    ["alturaDeReposabrazos","HpsaAtributosContenido18","","","",""],
    ["alturaDeTablero","HpsaAtributosContenido18","","","",""],
    ["alturaMaximaReposabrazos","HpsaAtributosContenido18","","","",""],
    ["anchoDeBase","HpsaAtributosContenido18","","","",""],
    ["anchoDeCorte","HpsaAtributosContenido18","","","",""],
    ["btu","HpsaAtributosContenido18","","","",""],
    ["cajaRinde","HpsaAtributosContenido18","","","",""],
    ["capacidadDeCarga","HpsaAtributosContenido18","","","",""],
    ["capacidadDeCorteEnMadera","HpsaAtributosContenido18","","","",""],
    ["capacidadDeSecado","HpsaAtributosContenido18","","","",""],
    ["capacidadDelTanqueDeCombustibl","HpsaAtributosContenido18","","","",""],
    ["cilindrada","HpsaAtributosContenido18","","","",""],
    ["diametroDeDescarga","HpsaAtributosContenido18","","","",""],
    ["diametroDePivote","HpsaAtributosContenido18","","","",""],
    ["diametroMaximoDePerforacionEnM","HpsaAtributosContenido18","","","",""],
    ["diametroParaDesague","HpsaAtributosContenido18","","","",""],
    ["distanciaDeInstalacion","HpsaAtributosContenido18","","","",""],
    ["espesorDePuertas","HpsaAtributosContenido18","","","",""],
    ["espesorDelVidrio","HpsaAtributosContenido18","","","",""],
    ["espesorMaximoDeCorte","HpsaAtributosContenido18","","","",""],
    ["gradosDeApertura","HpsaAtributosContenido18","","","",""],
    ["largoDeLaFibra","HpsaAtributosContenido18","","","",""],
    ["largoDeLaHelice","HpsaAtributosContenido18","","","",""],
    ["largoDelCable","HpsaAtributosContenido18","","","",""],
    ["largoMaximoDeLaCadena","HpsaAtributosContenido18","","","",""],
    ["medidaDeReposabrazos","HpsaAtributosContenido18","","","",""],
    ["metrosPorRollo","HpsaAtributosContenido18","","","",""],
    ["nivelesDeCoccion","HpsaAtributosContenido18","","","",""],
    ["potenciaNominal","HpsaAtributosContenido18","","","",""],
    ["profundidadDeCompactacion","HpsaAtributosContenido18","","","",""],
    ["profundidadMaximaDeCorte90","HpsaAtributosContenido18","","","",""],
    ["rendimientoDeSuperficieM2H","HpsaAtributosContenido18","","","",""],
    ["resistenciaPorBandeja","HpsaAtributosContenido18","","","",""],
    ["temperaturaMinimaDeTrabajo","HpsaAtributosContenido18","","","",""],
    ["tiempoDeDescarga","HpsaAtributosContenido18","","","",""],
    ["tiempoDeFuncionamientoALaMitad","HpsaAtributosContenido18","","","",""],
    ["tiempoMaximoDeProgramacion","HpsaAtributosContenido18","","","",""],
    ["tiempoMinimoDeProgramacion","HpsaAtributosContenido18","","","",""],
    ["alturaDeCerdas","HpsaAtributosContenido19","","","",""],
    ["alturaDeLaBase","HpsaAtributosContenido19","","","",""],
    ["alturaDeLaPlanta","HpsaAtributosContenido19","","","",""],
    ["alturaMaximaDeAlcance","HpsaAtributosContenido19","","","",""],
    ["alturaMinimaProducto","HpsaAtributosContenido19","","","",""],
    ["areaDeCoccion","HpsaAtributosContenido19","","","",""],
    ["aro","HpsaAtributosContenido19","","","",""],
    ["capacidadDeLavado","HpsaAtributosContenido19","","","",""],
    ["diametroDelNylon","HpsaAtributosContenido19","","","",""],
    ["fuerzaDeSujecion","HpsaAtributosContenido19","","","",""],
    ["largoDeLaEspada","HpsaAtributosContenido19","","","",""],
    ["medidaDelBrazo","HpsaAtributosContenido19","","","",""],
    ["presionNominalPn","HpsaAtributosContenido19","","","",""],
    ["resistenciaEnKilos","HpsaAtributosContenido19","","","",""],
    ["temperaturaMaximaDeTrabajo","HpsaAtributosContenido19","","","",""],
    ["abrillantador","HpsaAtributosContenido2","","","",""],
    ["aplicacion","HpsaAtributosContenido2","","","",""],
    ["aroma","HpsaAtributosContenido2","","","",""],
    ["camaraFrontal","HpsaAtributosContenido2","","","",""],
    ["capacidadDePesoPorCajon","HpsaAtributosContenido2","","","",""],
    ["capacidadDelHorno","HpsaAtributosContenido2","","","",""],
    ["controlConVoz","HpsaAtributosContenido2","","","",""],
    ["controlDeHumedad","HpsaAtributosContenido2","","","",""],
    ["diametroDeCanopla","HpsaAtributosContenido2","","","",""],
    ["distanciaEntreBisagras","HpsaAtributosContenido2","","","",""],
    ["dondeUsarlo","HpsaAtributosContenido2","¿Dónde usarlo?","","",""],
    ["duracionDeBateria","HpsaAtributosContenido2","Abrillantador","","",""],
    ["enfriadorEnPuerta","HpsaAtributosContenido2","Altura de la taza","","",""],
    ["espesorDeZocalo","HpsaAtributosContenido2","Altura de reposabrazos","","",""],
    ["funciones","HpsaAtributosContenido2","Altura de tablero","","",""],
    ["hidrorepelente","HpsaAtributosContenido2","Aplicación","","",""],
    ["interior","HpsaAtributosContenido2","Aroma","","",""],
    ["materialDeLaVisera","HpsaAtributosContenido2","Cámara frontal","","",""],
    ["materialDeTapaDeLaCubierta","HpsaAtributosContenido2","Capacidad del tanque de combustible","","",""],
    ["materialDelPlatoGiratorio","HpsaAtributosContenido2","Colección","","",""],
    ["medidaDeLaBandeja","HpsaAtributosContenido2","Control con voz","","",""],
    ["medidaDeLaPoza","HpsaAtributosContenido2","Control de humedad","","",""],
    ["medidaDeLaPuerta","HpsaAtributosContenido2","Diámetro de canopla","","",""],
    ["modeloDeTarjetaDeVideo","HpsaAtributosContenido2","Diámetro de pivote","","",""],
    ["modoDePreparacion","HpsaAtributosContenido2","Duración de batería","","",""],
    ["nivelDeDefinicion","HpsaAtributosContenido2","Enfriador en puerta","","",""],
    ["norma","HpsaAtributosContenido2","Espesor de zócalo","","",""],
    ["pasos","HpsaAtributosContenido2","Funciones","","",""],
    ["platoGiratorio","HpsaAtributosContenido2","Hidrorepelente","","",""],
    ["procesador","HpsaAtributosContenido2","Interior","","",""],
    ["programacion","HpsaAtributosContenido2","Largo de la fibra","","",""],
    ["propiedades","HpsaAtributosContenido2","Material de la visera","","",""],
    ["resistenciaMaximaImpacto","HpsaAtributosContenido2","Material de tapa de la cubierta","","",""],
    ["salanizado","HpsaAtributosContenido2","Material del plato giratorio","","",""],
    ["sistemaAntiDesborde","HpsaAtributosContenido2","Medida de la bandeja","","",""],
    ["sistemaInteractivo","HpsaAtributosContenido2","Medida de la poza","","",""],
    ["smartTv","HpsaAtributosContenido2","Medida de la puerta","","",""],
    ["tipoDeLavadero","HpsaAtributosContenido2","Modelo de tarjeta de video","","",""],
    ["tipoDePantalla","HpsaAtributosContenido2","Modo de preparación","","",""],
    ["ubicacion","HpsaAtributosContenido2","Nivel de definición","","",""],
    ["uso","HpsaAtributosContenido2","Norma","","",""],
    ["aberturaFrontal","HpsaAtributosContenido3","Pasos","","",""],
    ["aireador","HpsaAtributosContenido3","Plato Giratorio","","",""],
    ["antimicrobiano","HpsaAtributosContenido3","Procesador","","",""],
    ["antiperforante","HpsaAtributosContenido3","Programación","","",""],
    ["asaTelescopica","HpsaAtributosContenido3","Propiedades","","",""],
    ["autopropulsada","HpsaAtributosContenido3","Resistencia máxima impacto","","",""],
    ["cantidadDePuertas","HpsaAtributosContenido3","Salanizado","","",""],
    ["cartuchoReemplazable","HpsaAtributosContenido3","Sistema anti desborde","","",""],
    ["compatibilidad","HpsaAtributosContenido3","Sistema interactivo","","",""],
    ["condicionesDeInstalacion","HpsaAtributosContenido3","Smart TV","","",""],
    ["contenido","HpsaAtributosContenido3","Tiempo de funcionamiento a la mitad de carga","","",""],
    ["controlDeVapor","HpsaAtributosContenido3","Tipo de lavadero","","",""],
    ["corteDeIngleteDeGradoMaximoIzq","HpsaAtributosContenido3","Tipo de pantalla","","",""],
    ["deodorizador","HpsaAtributosContenido3","Ubicación","","",""],
    ["diagnosticoInteligente","HpsaAtributosContenido3","Uso","","",""],
    ["diseno","HpsaAtributosContenido3","Abertura frontal","","",""],
    ["disenoDePuerta","HpsaAtributosContenido3","Aireador","","",""],
    ["distanciaEntrePerillas","HpsaAtributosContenido3","Antimicrobiano","","",""],
    ["duchaTelefono","HpsaAtributosContenido3","Antiperforante","","",""],
    ["giratorio","HpsaAtributosContenido3","Asa telescópica","","",""],
    ["gradoDeGiro","HpsaAtributosContenido3","Autopropulsada","","",""],
    ["mangoExtensible","HpsaAtributosContenido3","Cantidad de puertas","","",""],
    ["materialDeLaCabeza","HpsaAtributosContenido3","Cartucho reemplazable","","",""],
    ["materialInternoDelAsiento","HpsaAtributosContenido3","Compatibilidad","","",""],
    ["materialInternoDelRespaldar","HpsaAtributosContenido3","Condiciones de instalación","","",""],
    ["medidaDeBandejasORepisas","HpsaAtributosContenido3","Contenido","","",""],
    ["medidasDeAlojamiento","HpsaAtributosContenido3","Control de vapor","","",""],
    ["nombreComun","HpsaAtributosContenido3","Corte de inglete de grado máximo - izquierda","","",""],
    ["numeroDeAspas","HpsaAtributosContenido3","Deodorizador","","",""],
    ["numeroDeEntradasHdmi","HpsaAtributosContenido3","Diagnóstico Inteligente","","",""],
    ["numeroDePerforacionesParaGrife","HpsaAtributosContenido3","Diámetro para desagüe","","",""],
    ["numeroDePiezasPorCaja","HpsaAtributosContenido3","Diseño","","",""],
    ["numeroDeRepisas","HpsaAtributosContenido3","Diseño de Puerta","","",""],
    ["potenciaDeExtraccion","HpsaAtributosContenido3","Ducha teléfono","","",""],
    ["potenciaDeParlantes","HpsaAtributosContenido3","Giratorio","","",""],
    ["recomendacionDeInstalacion","HpsaAtributosContenido3","Grado de giro","","",""],
    ["rotacion","HpsaAtributosContenido3","Grados de apertura","","",""],
    ["tipoDeCorredera","HpsaAtributosContenido3","Largo de la helice","","",""],
    ["tipoDeHorno","HpsaAtributosContenido3","Mango extensible","","",""],
    ["tipoDeMueble","HpsaAtributosContenido3","Material de la cabeza","","",""],
    ["tipoDePuerta","HpsaAtributosContenido3","Material interno del asiento","","",""],
    ["tipoDeQuemadores","HpsaAtributosContenido3","Material interno del respaldar","","",""],
    ["usuario","HpsaAtributosContenido3","Medida de bandejas o repisas","","",""],
    ["valvulaDeSeguridad","HpsaAtributosContenido3","Medida de reposabrazos","","",""],
    ["variedad","HpsaAtributosContenido3","Medidas de alojamiento","","",""],
    ["ventajas","HpsaAtributosContenido3","Nombre común","","",""],
    ["acabado","HpsaAtributosContenido4","Número de aspas","","",""],
    ["agentePropulsor","HpsaAtributosContenido4","Número de entradas HDMI","","",""],
    ["agujeroParaLasPiernas","HpsaAtributosContenido4","Número de perforaciones para grifería","","",""],
    ["aislamientoDeSonido","HpsaAtributosContenido4","Número de piezas por caja","","",""],
    ["bolsaParaPolvo","HpsaAtributosContenido4","Número de repisas","","",""],
    ["botonUsoContinuo","HpsaAtributosContenido4","Potencia de extracción","","",""],
    ["cantidadDeCanales","HpsaAtributosContenido4","Potencia de parlantes","","",""],
    ["cantidadDePerillas","HpsaAtributosContenido4","Profundidad máxima de corte 90°","","",""],
    ["cantidadDeResortes","HpsaAtributosContenido4","Recomendación de instalación","","",""],
    ["categoriaCemento","HpsaAtributosContenido4","Tiempo máximo de programación","","",""],
    ["cerrojoLateralInferior","HpsaAtributosContenido4","Tiempo mínimo de programación","","",""],
    ["conexionATierra","HpsaAtributosContenido4","Tipo de corredera","","",""],
    ["consumoDeAire","HpsaAtributosContenido4","Tipo de horno","","",""],
    ["densidadUnitaria","HpsaAtributosContenido4","Tipo de mueble","","",""],
    ["disponible","HpsaAtributosContenido4","Tipo de puerta","","",""],
    ["estilo","HpsaAtributosContenido4","Tipo de quemadores","","",""],
    ["indicadorDeCombustible","HpsaAtributosContenido4","Usuario","","",""],
    ["largoMinimoDeLaCadena","HpsaAtributosContenido4","Válvula de seguridad","","",""],
    ["materialDeHornillas","HpsaAtributosContenido4","Variedad","","",""],
    ["materialDeLaBase","HpsaAtributosContenido4","Ventajas","","",""],
    ["materialDeLasPatas","HpsaAtributosContenido4","Acabado","","",""],
    ["materialDeLasRuedas","HpsaAtributosContenido4","Agente propulsor","","",""],
    ["materialDeMandril","HpsaAtributosContenido4","Agujero para las piernas","","",""],
    ["materialDeRepisas","HpsaAtributosContenido4","Aislamiento de sonido","","",""],
    ["memoriaRam","HpsaAtributosContenido4","Alto con base","","",""],
    ["modoDeDescarga","HpsaAtributosContenido4","Ancho de corte","","",""],
    ["numeroDeBarras","HpsaAtributosContenido4","Bolsa para polvo","","",""],
    ["numeroDeColores","HpsaAtributosContenido4","Botón uso continuo","","",""],
    ["numeroDeEntradasRca","HpsaAtributosContenido4","Cantidad de canales","","",""],
    ["numeroDeJets","HpsaAtributosContenido4","Cantidad de perillas","","",""],
    ["numeroDeLuces","HpsaAtributosContenido4","Cantidad de resortes","","",""],
    ["numeroDePuertas","HpsaAtributosContenido4","Capacidad de carga","","",""],
    ["numeroDePuertasPiston","HpsaAtributosContenido4","Categoría cemento","","",""],
    ["perforaciones","HpsaAtributosContenido4","Cerrojo lateral inferior","","",""],
    ["posabrazos","HpsaAtributosContenido4","Conexión a tierra","","",""],
    ["procesadorDeComputo","HpsaAtributosContenido4","Consumo de aire","","",""],
    ["puertaConPiston","HpsaAtributosContenido4","Densidad unitaria","","",""],
    ["recargable","HpsaAtributosContenido4","Diámetro máximo de perforación en mampostería","","",""],
    ["reguladorDeAhorro","HpsaAtributosContenido4","Disponible","","",""],
    ["resistenteALaOxidacion","HpsaAtributosContenido4","Estilo","","",""],
    ["rosticero","HpsaAtributosContenido4","Indicador de combustible","","",""],
    ["soporteDeParaguas","HpsaAtributosContenido4","Largo mínimo de la cadena","","",""],
    ["tipoDeConductor","HpsaAtributosContenido4","Material de hornillas","","",""],
    ["tipoDeEnergia","HpsaAtributosContenido4","Material de la base","","",""],
    ["tipoDeLubricante","HpsaAtributosContenido4","Material de las patas","","",""],
    ["tipoDePulsador","HpsaAtributosContenido4","Material de las ruedas","","",""],
    ["tipoDeTirador","HpsaAtributosContenido4","Material de mandril","","",""],
    ["ubicacionDeLaConexionDeAgua","HpsaAtributosContenido4","Material de repisas","","",""],
    ["vision","HpsaAtributosContenido4","Memoria RAM","","",""],
    ["accesoFacilACarbones","HpsaAtributosContenido5","Metros por rollo","","",""],
    ["adhesivo","HpsaAtributosContenido5","Modo de descarga","","",""],
    ["anticorte","HpsaAtributosContenido5","Número de barras","","",""],
    ["aspasReversibles","HpsaAtributosContenido5","Número de colores","","",""],
    ["capacidadDelDiscoDuro","HpsaAtributosContenido5","Número de entradas RCA","","",""],
    ["cargadorIncluido","HpsaAtributosContenido5","Número de jets","","",""],
    ["diluyente","HpsaAtributosContenido5","Número de luces","","",""],
    ["disenoDePantalla","HpsaAtributosContenido5","Número de puertas","","",""],
    ["estantesAjustables","HpsaAtributosContenido5","Número de puertas pistón","","",""],
    ["expandible","HpsaAtributosContenido5","Perforaciones","","",""],
    ["granos","HpsaAtributosContenido5","Posabrazos","","",""],
    ["hojaRetractil","HpsaAtributosContenido5","Procesador de cómputo","","",""],
    ["impermeable","HpsaAtributosContenido5","Puerta con pistón","","",""],
    ["inalambrico","HpsaAtributosContenido5","Recargable","","",""],
    ["magnetico","HpsaAtributosContenido5","Regulador de ahorro","","",""],
    ["materialDeLaMesa","HpsaAtributosContenido5","Resistencia por bandeja","","",""],
    ["materialDeLosSillones","HpsaAtributosContenido5","Resistente a la oxidación","","",""],
    ["materialDeRespaldar","HpsaAtributosContenido5","Rosticero","","",""],
    ["materialDelTapiz","HpsaAtributosContenido5","Soporte de paraguas","","",""],
    ["modoDeRegulacionNivelesDeCorte","HpsaAtributosContenido5","Tipo de conductor","","",""],
    ["nucleosDelProcesador","HpsaAtributosContenido5","Tipo de energía","","",""],
    ["numeroDeCilindros","HpsaAtributosContenido5","Tipo de lubricante","","",""],
    ["numeroDeFunciones","HpsaAtributosContenido5","Tipo de pulsador","","",""],
    ["numeroDeParrillas","HpsaAtributosContenido5","Tipo de tirador","","",""],
    ["numeroDePuntos10cm","HpsaAtributosContenido5","Ubicación de la conexión de agua","","",""],
    ["oscilacionesSinCarga","HpsaAtributosContenido5","Visión","","",""],
    ["regulable","HpsaAtributosContenido5","Acceso fácil a carbones","","",""],
    ["repisaParaTeclado","HpsaAtributosContenido5","Adhesivo","","",""],
    ["resistenciaALaHumedad","HpsaAtributosContenido5","Ancho de base","","",""],
    ["resistenciaALasRayaduras","HpsaAtributosContenido5","Anticorte","","",""],
    ["resistenteAlAgua","HpsaAtributosContenido5","Aspas reversibles","","",""],
    ["sistemaDeRefrigeracion","HpsaAtributosContenido5","Caja rinde","","",""],
    ["tipoDeAjusteDeMandril","HpsaAtributosContenido5","Capacidad de corte en madera","","",""],
    ["tipoDeBisagra","HpsaAtributosContenido5","Capacidad del disco duro","","",""],
    ["tipoDeClavo","HpsaAtributosContenido5","Cargador incluído","","",""],
    ["tipoDeDiscoDuro","HpsaAtributosContenido5","Cilindrada","","",""],
    ["tipoDeEncendido","HpsaAtributosContenido5","Diluyente","","",""],
    ["tipoDeEstructura","HpsaAtributosContenido5","Diseño de pantalla","","",""],
    ["tipoDePasador","HpsaAtributosContenido5","Espesor del vidrio","","",""],
    ["tipoDeProcesoDeSoldar","HpsaAtributosContenido5","Espesor máximo de corte","","",""],
    ["tipoDeRack","HpsaAtributosContenido5","Estantes ajustables","","",""],
    ["tipoDeRecarga","HpsaAtributosContenido5","Expandible","","",""],
    ["velocidadMaxima","HpsaAtributosContenido5","Granos","","",""],
    ["alturaAjustable","HpsaAtributosContenido6","Hoja retráctil","","",""],
    ["anodoDeMagnesio","HpsaAtributosContenido6","Impermeable","","",""],
    ["bloqueoDeSeguridad","HpsaAtributosContenido6","Inalámbrico","","",""],
    ["calibre","HpsaAtributosContenido6","Largo máximo de la cadena","","",""],
    ["cantidadDeCuerpos","HpsaAtributosContenido6","Magnético","","",""],
    ["caudalDeChorroAjustable","HpsaAtributosContenido6","Material de la mesa","","",""],
    ["controlElectronicoDeVelocidad","HpsaAtributosContenido6","Material de los sillones","","",""],
    ["desfogueDeAgua","HpsaAtributosContenido6","Material de respaldar","","",""],
    ["eficienciaEnergetica","HpsaAtributosContenido6","Material del tapiz","","",""],
    ["empunaduraAntiVibracion","HpsaAtributosContenido6","Modo de regulación niveles de corte","","",""],
    ["entradas","HpsaAtributosContenido6","Núcleos del procesador","","",""],
    ["extraccionDePolvo","HpsaAtributosContenido6","Número de cilindros","","",""],
    ["forrado","HpsaAtributosContenido6","Número de funciones","","",""],
    ["fuenteDeAlimentacion","HpsaAtributosContenido6","Número de parrillas","","",""],
    ["iluminacionLed","HpsaAtributosContenido6","Número de puntos / 10cm","","",""],
    ["lectorDeHuellas","HpsaAtributosContenido6","Oscilaciones sin carga","","",""],
    ["lejia","HpsaAtributosContenido6","Profundidad de compactación","","",""],
    ["luzEnHorno","HpsaAtributosContenido6","Regulable","","",""],
    ["materialDeBase","HpsaAtributosContenido6","Repisa para teclado","","",""],
    ["materialDeReposabrazos","HpsaAtributosContenido6","Resistencia a la humedad","","",""],
    ["materialDelFondo","HpsaAtributosContenido6","Resistencia a las rayaduras","","",""],
    ["numeroDeEspejos","HpsaAtributosContenido6","Resistente al agua","","",""],
    ["numeroDeLlaves","HpsaAtributosContenido6","Sistema de refrigeración","","",""],
    ["paredesAutolimpiantes","HpsaAtributosContenido6","Temperatura mínima de trabajo","","",""],
    ["pasoDeLuz","HpsaAtributosContenido6","Tipo de ajuste de mandril","","",""],
    ["proporcionDeFallo","HpsaAtributosContenido6","Tipo de bisagra","","",""],
    ["puertasDesmontables","HpsaAtributosContenido6","Tipo de clavo","","",""],
    ["requiereInstalacion","HpsaAtributosContenido6","Tipo de disco duro","","",""],
    ["resistenciaSalina","HpsaAtributosContenido6","Tipo de encendido","","",""],
    ["sistemaDeApertura","HpsaAtributosContenido6","Tipo de estructura","","",""],
    ["sistemaDeDrenado","HpsaAtributosContenido6","Tipo de pasador","","",""],
    ["sistemaDeUnionDePiezas","HpsaAtributosContenido6","Tipo de proceso de soldar","","",""],
    ["sistemaOperativoCompatible","HpsaAtributosContenido6","Tipo de rack","","",""],
    ["superficie","HpsaAtributosContenido6","Tipo de recarga","","",""],
    ["termostato","HpsaAtributosContenido6","Altura ajustable","","",""],
    ["textura","HpsaAtributosContenido6","Altura máxima reposabrazos","","",""],
    ["tipoDeCaida","HpsaAtributosContenido6","Ánodo de magnesio","","",""],
    ["tipoDeCocina","HpsaAtributosContenido6","Bloqueo de seguridad","","",""],
    ["tipoDeConexion","HpsaAtributosContenido6","BTU","","",""],
    ["tipoDeGas","HpsaAtributosContenido6","Calibre","","",""],
    ["tipoDeHoja","HpsaAtributosContenido6","Cantidad de cuerpos","","",""],
    ["tipoDeLuz","HpsaAtributosContenido6","Capacidad de secado","","",""],
    ["tipoDePanel","HpsaAtributosContenido6","Caudal de chorro ajustable","","",""],
    ["tipoDeVidrio","HpsaAtributosContenido6","Control electrónico de velocidad","","",""],
    ["ajustable","HpsaAtributosContenido7","Desfogue de agua","","",""],
    ["antiInflamable","HpsaAtributosContenido7","Eficiencia energética","","",""],
    ["apagadoAutomatico","HpsaAtributosContenido7","Empuñadura anti-vibración","","",""],
    ["botonDeAbertura","HpsaAtributosContenido7","Entradas","","",""],
    ["cabezaRegulable","HpsaAtributosContenido7","Espesor de puertas","","",""],
    ["capacidadDeAbsorcion","HpsaAtributosContenido7","Extracción de polvo","","",""],
    ["cicloDeTrabajo","HpsaAtributosContenido7","Forrado","","",""],
    ["corteMaximoEnDiagonal","HpsaAtributosContenido7","Fuente de alimentación","","",""],
    ["extraccionDeHumedad","HpsaAtributosContenido7","Iluminación led","","",""],
    ["genero","HpsaAtributosContenido7","Lector de huellas","","",""],
    ["grill","HpsaAtributosContenido7","Lejía","","",""],
    ["inversorIncorporado","HpsaAtributosContenido7","Luz en horno","","",""],
    ["jetsHidromasajes","HpsaAtributosContenido7","Material De Base","","",""],
    ["lavable","HpsaAtributosContenido7","Material de reposabrazos","","",""],
    ["luzPiloto","HpsaAtributosContenido7","Material del fondo","","",""],
    ["mantenimiento","HpsaAtributosContenido7","Número de espejos","","",""],
    ["materialDeLaFunda","HpsaAtributosContenido7","Número de llaves","","",""],
    ["materialDeRelleno","HpsaAtributosContenido7","Paredes autolimpiantes","","",""],
    ["materialDelCuerpo","HpsaAtributosContenido7","Paso de luz","","",""],
    ["materialDelTambor","HpsaAtributosContenido7","Potencia nominal","","",""],
    ["numeroDeCajones","HpsaAtributosContenido7","Proporcion de Fallo","","",""],
    ["numeroDeMotores","HpsaAtributosContenido7","Puertas desmontables","","",""],
    ["oscilante","HpsaAtributosContenido7","Rendimiento de superficie (m2/h)","","",""],
    ["posicionesDeEmpunadura","HpsaAtributosContenido7","Requiere instalación","","",""],
    ["puertoEthernet","HpsaAtributosContenido7","Resistencia salina","","",""],
    ["pureza","HpsaAtributosContenido7","Sistema de apertura","","",""],
    ["reguladorDePaseDeAgua","HpsaAtributosContenido7","Sistema de drenado","","",""],
    ["reguladorDePresion","HpsaAtributosContenido7","Sistema de union de piezas","","",""],
    ["resistenciaALosSolventes","HpsaAtributosContenido7","Sistema operativo compatible","","",""],
    ["resistenteACambiosDeTemperatur","HpsaAtributosContenido7","Superficie","","",""],
    ["resistenteAlFuego","HpsaAtributosContenido7","Termostato","","",""],
    ["ruedas","HpsaAtributosContenido7","Textura","","",""],
    ["tipoDeAcabado","HpsaAtributosContenido7","Tiempo de descarga","","",""],
    ["tipoDeAislamiento","HpsaAtributosContenido7","Tipo de caída","","",""],
    ["tipoDeBorde","HpsaAtributosContenido7","Tipo de cocina","","",""],
    ["tipoDeCilindro","HpsaAtributosContenido7","Tipo de conexión","","",""],
    ["tipoDeColor","HpsaAtributosContenido7","Tipo de gas","","",""],
    ["tipoDeCorrederas","HpsaAtributosContenido7","Tipo de hoja","","",""],
    ["tipoDePestillo","HpsaAtributosContenido7","Tipo de luz","","",""],
    ["tipoDeRiego","HpsaAtributosContenido7","Tipo de panel","","",""],
    ["tipoDeUso","HpsaAtributosContenido7","Tipo de vidrio","","",""],
    ["wiFi","HpsaAtributosContenido7","Ajustable","","",""],
    ["accesoRemoto","HpsaAtributosContenido8","Anti inflamable","","",""],
    ["acustico","HpsaAtributosContenido8","Apagado automático","","",""],
    ["agarre","HpsaAtributosContenido8","Botón de abertura","","",""],
    ["aislamientoTermico","HpsaAtributosContenido8","Cabeza regulable","","",""],
    ["aislante","HpsaAtributosContenido8","Capacidad de absorción","","",""],
    ["alimentacionCombustible","HpsaAtributosContenido8","Ciclo de trabajo","","",""],
    ["antiRayaduras","HpsaAtributosContenido8","Corte máximo en diagonal","","",""],
    ["camaraWeb","HpsaAtributosContenido8","Diámetro de descarga","","",""],
    ["cantidadDePlacas","HpsaAtributosContenido8","Distancia de instalación","","",""],
    ["capacidadConductivaElectrica","HpsaAtributosContenido8","Extracción de humedad","","",""],
    ["cerraduraAuxiliar","HpsaAtributosContenido8","Género","","",""],
    ["cerraduraLateralSuperior","HpsaAtributosContenido8","Grill","","",""],
    ["colorDeTablero","HpsaAtributosContenido8","Inversor incorporado","","",""],
    ["compatibilidadConPiscinasDeSal","HpsaAtributosContenido8","Jets hidromasajes","","",""],
    ["controlRemoto","HpsaAtributosContenido8","Largo del cable","","",""],
    ["convector","HpsaAtributosContenido8","Lavable","","",""],
    ["criterioDeDesgasteAc","HpsaAtributosContenido8","Luz piloto","","",""],
    ["estabilizadorDeVoltaje","HpsaAtributosContenido8","Mantenimiento","","",""],
    ["grado","HpsaAtributosContenido8","Material de la funda","","",""],
    ["hipoalergenico","HpsaAtributosContenido8","Material de relleno","","",""],
    ["incluyeSombrilla","HpsaAtributosContenido8","Material del cuerpo","","",""],
    ["ip","HpsaAtributosContenido8","Material del tambor","","",""],
    ["materialDeLaTela","HpsaAtributosContenido8","Niveles de cocción","","",""],
    ["materialDeLasSillas","HpsaAtributosContenido8","Número de cajones","","",""],
    ["materialDeUso","HpsaAtributosContenido8","Número de motores","","",""],
    ["materialDelMarco","HpsaAtributosContenido8","Oscilante","","",""],
    ["numeroDeBolsillos","HpsaAtributosContenido8","Posiciones de empuñadura","","",""],
    ["numeroDeCiclos","HpsaAtributosContenido8","Puerto ethernet","","",""],
    ["numeroDeNiveles","HpsaAtributosContenido8","Pureza","","",""],
    ["numeroDePozas","HpsaAtributosContenido8","Regulador de pase de agua","","",""],
    ["numeroDeQuemadores","HpsaAtributosContenido8","Regulador de presión","","",""],
    ["presentacion","HpsaAtributosContenido8","Resistencia a los solventes","","",""],
    ["relleno","HpsaAtributosContenido8","Resistente a cambios de temperatura","","",""],
    ["resistenteALaHumedad","HpsaAtributosContenido8","Resistente al fuego","","",""],
    ["salidas","HpsaAtributosContenido8","Ruedas","","",""],
    ["termometro","HpsaAtributosContenido8","Temperatura máxima de trabajo","","",""],
    ["tipoDeAgua","HpsaAtributosContenido8","Tipo de acabado","","",""],
    ["tipoDeAro","HpsaAtributosContenido8","Tipo de aislamiento","","",""],
    ["tipoDeCierre","HpsaAtributosContenido8","Tipo de borde","","",""],
    ["tipoDeFijacion","HpsaAtributosContenido8","Tipo de cilindro","","",""],
    ["tipoDeFiltro","HpsaAtributosContenido8","Tipo de Color","","",""],
    ["tipoDePunta","HpsaAtributosContenido8","Tipo de correderas","","",""],
    ["toxicidad","HpsaAtributosContenido8","Tipo de pestillo","","",""],
    ["ventilacion","HpsaAtributosContenido8","Tipo de riego","","",""],
    ["vidrioTemplado","HpsaAtributosContenido8","Tipo de uso","","",""],
    ["voltajeEnVacio","HpsaAtributosContenido8","Wi Fi","","",""],
    ["acabadoDeBorde","HpsaAtributosContenido9","Acceso remoto","","",""],
    ["apilable","HpsaAtributosContenido9","Acústico","","",""],
    ["aplicadorEnLaTapa","HpsaAtributosContenido9","Agarre","","",""],
    ["apoyaBrazosRegulable","HpsaAtributosContenido9","Aislamiento térmico","","",""],
    ["cantidadDePivotes","HpsaAtributosContenido9","Aislante","","",""],
    ["cantidadPorEmpaque","HpsaAtributosContenido9","Alimentación/Combustible","","",""],
    ["capacidadDeCorteEnAcero","HpsaAtributosContenido9","Altura de cerdas","","",""],
    ["cerraduraPrincipal","HpsaAtributosContenido9","Altura de la base","","",""],
    ["ciclos","HpsaAtributosContenido9","Anti rayaduras","","",""],
    ["consumoDeCombustible","HpsaAtributosContenido9","Área de cocción","","",""],
    ["deteccionDeMovimiento","HpsaAtributosContenido9","Cámara web","","",""],
    ["diametroDePerforacion","HpsaAtributosContenido9","Cantidad de placas","","",""],
    ["escurridero","HpsaAtributosContenido9","Capacidad conductiva eléctrica","","",""],
    ["estandar","HpsaAtributosContenido9","Cerradura auxiliar","","",""],
    ["filtroDePelusas","HpsaAtributosContenido9","Cerradura lateral superior","","",""],
    ["filtros","HpsaAtributosContenido9","Color de tablero","","",""],
    ["flexible","HpsaAtributosContenido9","Compatibilidad con piscinas de sal","","",""],
    ["frecuenciaDeUso","HpsaAtributosContenido9","Control remoto","","",""],
    ["freno","HpsaAtributosContenido9","Convector","","",""],
    ["giroLateral","HpsaAtributosContenido9","Criterio de desgaste (Ac)","","",""],
    ["incluyeTapaDeCubierta","HpsaAtributosContenido9","Diámetro del nylon","","",""],
    ["materialDeLosCojines","HpsaAtributosContenido9","Estabilizador de voltaje","","",""],
    ["materialDePerillas","HpsaAtributosContenido9","Grado","","",""],
    ["materialDePuertas","HpsaAtributosContenido9","Hipoalergenico","","",""],
    ["nivelesDeAgua","HpsaAtributosContenido9","Incluye sombrilla","","",""],
    ["numeroDeNivelesDeCorte","HpsaAtributosContenido9","IP","","",""],
    ["numeroDeProgramasDeSecado","HpsaAtributosContenido9","Largo de la espada","","",""],
    ["portatil","HpsaAtributosContenido9","Material de la tela","","",""],
    ["programas","HpsaAtributosContenido9","Material de las sillas","","",""],
    ["proporcionMezcla","HpsaAtributosContenido9","Material de uso","","",""],
    ["reflectivo","HpsaAtributosContenido9","Material del marco","","",""],
    ["reguladorDeLlama","HpsaAtributosContenido9","Medida del brazo","","",""],
    ["repisasRemovibles","HpsaAtributosContenido9","Número de bolsillos","","",""],
    ["requerimientoEspecial","HpsaAtributosContenido9","Número de ciclos","","",""],
    ["resistenciaAlFuego","HpsaAtributosContenido9","Número de niveles","","",""],
    ["resistenciaDialectrica","HpsaAtributosContenido9","Número de pozas","","",""],
    ["resistenteAlDesgaste","HpsaAtributosContenido9","Número de quemadores","","",""],
    ["sistemaAntiGoteo","HpsaAtributosContenido9","Presentación","","",""],
    ["sistemaDeCierre","HpsaAtributosContenido9","Relleno","","",""],
    ["tecnologiaCelular","HpsaAtributosContenido9","Resistencia en kilos","","",""],
    ["timer","HpsaAtributosContenido9","Resistente a la humedad","","",""],
    ["tipoDeCana","HpsaAtributosContenido9","Salidas","","",""],
    ["tipoDeCarga","HpsaAtributosContenido9","Termómetro","","",""],
    ["tipoDePatas","HpsaAtributosContenido9","Tipo de agua","","",""],
    ["tipoDeResortes","HpsaAtributosContenido9","Tipo de aro","","",""],
    ["tipoDeRosca","HpsaAtributosContenido9","Tipo de cierre","","",""],
    ["cargadoEnWeb","HpsaAtributosDeSeguimiento","Tipo de fijación","","",""],
    ["coleccionGlovo","HpsaAtributosDeSeguimiento","Tipo de filtro","","",""],
    ["consultaDeStockAte","HpsaAtributosDeSeguimiento","Tipo de punta","","",""],
    ["crossSellingComplemento","HpsaAtributosDeSeguimiento","Toxicidad","","",""],
    ["crossSellingInstalacion","HpsaAtributosDeSeguimiento","Ventilación","","",""],
    ["crossSellingVentaProyecto","HpsaAtributosDeSeguimiento","Vidrio templado","","",""],
    ["enriquecimientoPrimeraInstanci","HpsaAtributosDeSeguimiento","Acabado de borde","","",""],
    ["estadoDeFichaTecnica","HpsaAtributosDeSeguimiento","Altura de la planta","","",""],
    ["estadoFichaTecnicaProv","HpsaAtributosDeSeguimiento","Altura máxima de alcance","","",""],
    ["estadoFoto","HpsaAtributosDeSeguimiento","Altura mínima producto","","",""],
    ["estadoFotoTxt","HpsaAtributosDeSeguimiento","Apilable","","",""],
    ["estadoManualInstalacion","HpsaAtributosDeSeguimiento","Aplicador en la tapa","","",""],
    ["estadoManualUsuario","HpsaAtributosDeSeguimiento","Apoya brazos regulable","","",""],
    ["estadoParaCargarEnWeb","HpsaAtributosDeSeguimiento","Aro","","",""],
    ["estadoVideo","HpsaAtributosDeSeguimiento","Cantidad de pivotes","","",""],
    ["fechaDeCargaDesplanogramado","HpsaAtributosDeSeguimiento","Cantidad por empaque","","",""],
    ["fechaDeCargaFichaTecnica","HpsaAtributosDeSeguimiento","Capacidad de lavado","","",""],
    ["fechaDeCargaFotoCompleta","HpsaAtributosDeSeguimiento","Cerradura principal","","",""],
    ["fechaDeCargaFotoPim","HpsaAtributosDeSeguimiento","Ciclos","","",""],
    ["fechaDeCargaLogistica","HpsaAtributosDeSeguimiento","Consumo de combustible","","",""],
    ["fechaDeCargaParaBl","HpsaAtributosDeSeguimiento","Detección de movimiento","","",""],
    ["fechaDeCargaPli2","HpsaAtributosDeSeguimiento","Escurridero","","",""],
    ["fechaDeCargaWeb","HpsaAtributosDeSeguimiento","Estándar","","",""],
    ["fechaDeEntregaBl","HpsaAtributosDeSeguimiento","Filtro de pelusas","","",""],
    ["fechaDeEntregaDeCorreccion","HpsaAtributosDeSeguimiento","Filtros","","",""],
    ["fechaDeEnvioCrossWebservice","HpsaAtributosDeSeguimiento","Flexible","","",""],
    ["fechaDeEnvioDeCorreccion","HpsaAtributosDeSeguimiento","Frecuencia de uso","","",""],
    ["fechaDeEnvioDeWebservices","HpsaAtributosDeSeguimiento","Freno","","",""],
    ["fichaTecnicaImpresaVisual","HpsaAtributosDeSeguimiento","Fuerza de sujeción","","",""],
    ["fotoCompleta","HpsaAtributosDeSeguimiento","Giro lateral","","",""],
    ["nombreDeArchivo","HpsaAtributosDeSeguimiento","Incluye tapa de cubierta","","",""],
    ["nombreDeJefeDeLinea","HpsaAtributosDeSeguimiento","Material de los cojines","","",""],
    ["observacionDeFoto","HpsaAtributosDeSeguimiento","Material de perillas","","",""],
    ["observacionOFechaEstimadaDeLle","HpsaAtributosDeSeguimiento","Material de puertas","","",""],
    ["seleccionGlovo","HpsaAtributosDeSeguimiento","Niveles de agua","","",""],
    ["supercoleccionGlovo","HpsaAtributosDeSeguimiento","Número de niveles de corte","","",""],
    ["ultimaModificacion","HpsaAtributosDeSeguimiento","Número de programas de secado","","",""],
    ["ultimaModificacionTxt","HpsaAtributosDeSeguimiento","Portátil","","",""],
    ["ultimaRevisionDeImagenes","HpsaAtributosDeSeguimiento","Presión nominal (pn)","","",""],
    ["ultimoUsuarioEnModificar","HpsaAtributosDeSeguimiento","Programas","","",""],
    ["ultimoUsuarioEnModificarTxt","HpsaAtributosDeSeguimiento","Proporción mezcla","","",""],
    ["urlDetalle","HpsaAtributosDeSeguimiento","Reflectivo","","",""],
    ["urlImagenLt","HpsaAtributosDeSeguimiento","Regulador de llama","","",""],
    ["validacionDeMedidasDeProducto","HpsaAtributosDeSeguimiento","Repisas removibles","","",""],
    ["validacionDeMedidasDeUndLog","HpsaAtributosDeSeguimiento","Requerimiento especial","","",""],
    ["validacionDePesosDeProducto","HpsaAtributosDeSeguimiento","Resistencia al fuego","","",""],
    ["validacionDePesosDeUndLog","HpsaAtributosDeSeguimiento","Resistencia dialéctrica","","",""],
    ["dificultadDelServicio","HpsaAtributosDeServicios","Resistente al desgaste","","",""],
    ["servicioECommerce","HpsaAtributosDeServicios","Sistema anti goteo","","",""],
    ["servicioGratuito","HpsaAtributosDeServicios","Sistema de cierre","","",""],
    ["tipoDeServicio","HpsaAtributosDeServicios","Tecnología celular","","",""],
    ["clusterDeSurtido","HpsaAtributosDeSurtido","Timer","","",""],
    ["fechaDeFin","HpsaAtributosDeSurtido","Tipo de caña","","",""],
    ["fechaDeInicio","HpsaAtributosDeSurtido","Tipo de carga","","",""],
    ["longtail","HpsaAtributosDeSurtido","Tipo de patas","","",""],
    ["alturaDeLaUnidadLogistica","HpsaAtributosLogisticos","Tipo de resortes","","",""],
    ["alturaDelMasterpackLogistica","HpsaAtributosLogisticos","Tipo de rosca","","",""],
    ["alturaDelProducto","HpsaAtributosLogisticos","Cargado en Web","","",""],
    ["anchoDeLaUnidadLogistica","HpsaAtributosLogisticos","COLECCION_GLOVO","","",""],
    ["anchoDelMasterpackLogistica","HpsaAtributosLogisticos","CONSULTA_DE_STOCK_ATE","","",""],
    ["anchoDelProducto","HpsaAtributosLogisticos","CROSS_SELLING_COMPLEMENTO","","",""],
    ["bigTicket","HpsaAtributosLogisticos","CROSS_SELLING_INSTALACION","","",""],
    ["cantidadDelMasterpackLogistica","HpsaAtributosLogisticos","CROSS_SELLING_VENTA_PROYECTO","","",""],
    ["densidad","HpsaAtributosLogisticos","Enriquecimiento Primera Instancia","","",""],
    ["despachoCd","HpsaAtributosLogisticos","Estado de Ficha tecnica","","",""],
    ["diametroDelProducto","HpsaAtributosLogisticos","ESTADO_FICHA_TECNICA_PROV","","",""],
    ["dun14","HpsaAtributosLogisticos","ESTADO_FOTO","","",""],
    ["ean","HpsaAtributosLogisticos","ESTADO_FOTO_TXT","","",""],
    ["empiochado","HpsaAtributosLogisticos","ESTADO_MANUAL_INSTALACION","","",""],
    ["logistica","HpsaAtributosLogisticos","ESTADO_MANUAL_USUARIO","","",""],
    ["medidaDeProductosEnCombo","HpsaAtributosLogisticos","ESTADO_PARA_CARGAR_EN_WEB","","",""],
    ["medidas","HpsaAtributosLogisticos","ESTADO_VIDEO","","",""],
    ["paisDeProcedencia","HpsaAtributosLogisticos","Fecha de carga  para  B&L","","",""],
    ["perecible","HpsaAtributosLogisticos","Fecha de Creación STEP","","",""],
    ["pesoDeLaUnidadLogistica","HpsaAtributosLogisticos","Fecha de entrega B&L","","",""],
    ["pesoDelMasterpackLogistica","HpsaAtributosLogisticos","FECHA_DE_CARGA_DESPLANOGRAMADO","","",""],
    ["pesoDelProducto","HpsaAtributosLogisticos","FECHA_DE_CARGA_FICHA_TECNICA","","",""],
    ["productoPeligroso","HpsaAtributosLogisticos","FECHA_DE_CARGA_FOTO_COMPLETA","","",""],
    ["productosSensibles","HpsaAtributosLogisticos","FECHA_DE_CARGA_FOTO_PIM","","",""],
    ["profundidadDeLaUnidadLogistica","HpsaAtributosLogisticos","FECHA_DE_CARGA_LOGISTICA","","",""],
    ["profundidadDelMasterpackLogist","HpsaAtributosLogisticos","FECHA_DE_CARGA_WEB","","",""],
    ["profundidadDelProducto","HpsaAtributosLogisticos","FECHA_DE_ENTREGA_DE_CORRECCION","","",""],
    ["tipoCodigoEan","HpsaAtributosLogisticos","FECHA_DE_ENVIO_CROSS_WEBSERVIC","","",""],
    ["tipoDelMasterpackLogistica","HpsaAtributosLogisticos","FECHA_DE_ENVIO_DE_CORRECCION","","",""],
    ["unidadDeMedidaDeInventarioUmi","HpsaAtributosLogisticos","FECHA_DE_ENVIO_DE_WEBSERVICES","","",""],
    ["volumenDeLaUnidadLogistica","HpsaAtributosLogisticos","FICHA_TECNICA_IMPRESA_VISUAL","","",""]
    
]

module.exports={map}